fix deploy script

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -77,26 +77,43 @@ jobs:
             --parameters commands="[\"sudo docker pull ${{ steps.get_ecr_url.outputs.ECR_REPO_URL }}:latest\", \"sudo /usr/local/bin/docker-compose -f /home/ec2-user/docker-compose.api.yaml pull\", \"sudo /usr/local/bin/docker-compose -f /home/ec2-user/docker-compose.api.yaml up -d --remove-orphans\", \"sudo /usr/local/bin/docker-compose -f /home/ec2-user/docker-compose.workers.yaml pull\", \"sudo /usr/local/bin/docker-compose -f /home/ec2-user/docker-compose.workers.yaml up -d --remove-orphans\"]" \
             --region ${{ secrets.AWS_REGION }} \
             --query "Command.CommandId" --output text)
-
+          
           echo "SSM Command ID: $COMMAND_ID"
-
-          aws ssm wait command-executed \
-            --command-id $COMMAND_ID \
-            --instance-id ${INSTANCE_IDS_ARRAY[0]} \
-            --region ${{ secrets.AWS_REGION }}
-
-          echo "SSM Command completed."
-
+          
+          echo "Waiting for command to execute..."
+          sleep 30 # Wait for 30 seconds to allow command to execute
+          
           echo "Retrieving SSM Command Output..."
-          aws ssm get-command-invocation \
+          COMMAND_OUTPUT=$(aws ssm get-command-invocation \
             --command-id $COMMAND_ID \
             --instance-id ${INSTANCE_IDS_ARRAY[0]} \
             --query "StandardOutputContent" --output text \
-            --region ${{ secrets.AWS_REGION }}
-
+            --region ${{ secrets.AWS_REGION }})
+          
+          echo "Standard Output:"
+          echo "$COMMAND_OUTPUT"
+          
           echo "Retrieving SSM Command Error Output..."
-          aws ssm get-command-invocation \
+          COMMAND_ERROR_OUTPUT=$(aws ssm get-command-invocation \
             --command-id $COMMAND_ID \
             --instance-id ${INSTANCE_IDS_ARRAY[0]} \
             --query "StandardErrorContent" --output text \
-            --region ${{ secrets.AWS_REGION }}
+            --region ${{ secrets.AWS_REGION }})
+          
+          echo "Standard Error:"
+          echo "$COMMAND_ERROR_OUTPUT"
+          
+          COMMAND_STATUS=$(aws ssm get-command-invocation \
+            --command-id $COMMAND_ID \
+            --instance-id ${INSTANCE_IDS_ARRAY[0]} \
+            --query "Status" --output text \
+            --region ${{ secrets.AWS_REGION }})
+          
+          echo "SSM Command Status: $COMMAND_STATUS"
+          
+          if [ "$COMMAND_STATUS" != "Success" ]; then
+            echo "Error: SSM Command failed on instance ${INSTANCE_IDS_ARRAY[0]}."
+            exit 1
+          fi
+          
+          echo "SSM Command completed successfully."
